{
 "bad": false,
 "new_version": "1.9.10",
 "new_version_attempts": {
  "1.7.13": 3.000000000000001,
  "1.7.14": 3.000000000000001,
  "1.7.15": 3.000000000000001,
  "1.7.16": 3.200000000000001,
  "1.8.0": 3.4000000000000012,
  "1.8.11": 3.4000000000000004,
  "1.8.12": 0,
  "1.8.2": 0.3999999999999999,
  "1.8.3": 3.4000000000000012,
  "1.8.5": 3.000000000000001,
  "1.9.0": 3.200000000000001,
  "1.9.1": 3.200000000000001,
  "1.9.10": 1,
  "1.9.2": 2.4000000000000004,
  "1.9.3": 3.000000000000001,
  "1.9.4": 0.19999999999999996
 },
 "new_version_errors": {
  "1.7.13": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/9927200141'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Cannot solve the request because of: dagster_gcp * cannot be installed because there are no viable options:\n\u2514\u2500 dagster_gcp 0.6.5 would require\n   \u2514\u2500 dagster_pandas *, which cannot be installed because there are no viable options:\n      \u251C\u2500 dagster_pandas 0.6.7.post0 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.post0.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.7 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7 | 0.6.7 | 0.6.7 | 0.6.7 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.6 would require\n      \u2502  \u2514\u2500 dagster 0.6.6.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.6 | 0.6.6 | 0.6.6 | 0.6.6 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.5 would require\n      \u2502  \u2514\u2500 dagster 0.6.5.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.5 | 0.6.5 | 0.6.5 | 0.6.5 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u2514\u2500 dagster_pandas 0.6.4 would require\n         \u2514\u2500 dagster 0.6.4.*, which cannot be installed because there are no viable options:\n            \u2514\u2500 dagster 0.6.4 | 0.6.4 | 0.6.4 would require\n               \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n\n                </pre>\n                </div>\n                </details>",
  "1.7.14": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10030862442'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Cannot solve the request because of: dagster_gcp * cannot be installed because there are no viable options:\n\u2514\u2500 dagster_gcp 0.6.5 would require\n   \u2514\u2500 dagster_pandas *, which cannot be installed because there are no viable options:\n      \u251C\u2500 dagster_pandas 0.6.7.post0 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.post0.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.7 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7 | 0.6.7 | 0.6.7 | 0.6.7 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.6 would require\n      \u2502  \u2514\u2500 dagster 0.6.6.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.6 | 0.6.6 | 0.6.6 | 0.6.6 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.5 would require\n      \u2502  \u2514\u2500 dagster 0.6.5.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.5 | 0.6.5 | 0.6.5 | 0.6.5 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u2514\u2500 dagster_pandas 0.6.4 would require\n         \u2514\u2500 dagster 0.6.4.*, which cannot be installed because there are no viable options:\n            \u2514\u2500 dagster 0.6.4 | 0.6.4 | 0.6.4 would require\n               \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n\n                </pre>\n                </div>\n                </details>",
  "1.7.15": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10124527170'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Cannot solve the request because of: dagster_gcp * cannot be installed because there are no viable options:\n\u2514\u2500 dagster_gcp 0.6.5 would require\n   \u2514\u2500 dagster_pandas *, which cannot be installed because there are no viable options:\n      \u251C\u2500 dagster_pandas 0.6.7.post0 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.post0.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.7 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7 | 0.6.7 | 0.6.7 | 0.6.7 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.6 would require\n      \u2502  \u2514\u2500 dagster 0.6.6.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.6 | 0.6.6 | 0.6.6 | 0.6.6 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.5 would require\n      \u2502  \u2514\u2500 dagster 0.6.5.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.5 | 0.6.5 | 0.6.5 | 0.6.5 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u2514\u2500 dagster_pandas 0.6.4 would require\n         \u2514\u2500 dagster 0.6.4.*, which cannot be installed because there are no viable options:\n            \u2514\u2500 dagster 0.6.4 | 0.6.4 | 0.6.4 would require\n               \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n\n                </pre>\n                </div>\n                </details>",
  "1.7.16": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10282814354'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Cannot solve the request because of: dagster_gcp * cannot be installed because there are no viable options:\n\u2514\u2500 dagster_gcp 0.6.5 would require\n   \u2514\u2500 dagster_pandas *, which cannot be installed because there are no viable options:\n      \u251C\u2500 dagster_pandas 0.6.7.post0 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.post0.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.7 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7 | 0.6.7 | 0.6.7 | 0.6.7 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.6 would require\n      \u2502  \u2514\u2500 dagster 0.6.6.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.6 | 0.6.6 | 0.6.6 | 0.6.6 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.5 would require\n      \u2502  \u2514\u2500 dagster 0.6.5.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.5 | 0.6.5 | 0.6.5 | 0.6.5 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u2514\u2500 dagster_pandas 0.6.4 would require\n         \u2514\u2500 dagster 0.6.4.*, which cannot be installed because there are no viable options:\n            \u2514\u2500 dagster 0.6.4 | 0.6.4 | 0.6.4 would require\n               \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n\n                </pre>\n                </div>\n                </details>",
  "1.8.0": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10350363620'>bot CI job</a>) @ main\n                <details>\n                <div align=\"left\">\n                <pre>\n                linux_64_: Cannot solve the request because of: dagster_gcp * cannot be installed because there are no viable options:\n\u2514\u2500 dagster_gcp 0.6.5 would require\n   \u2514\u2500 dagster_pandas *, which cannot be installed because there are no viable options:\n      \u251C\u2500 dagster_pandas 0.6.7.post0 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.post0.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 | 0.6.7.post0 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.7 would require\n      \u2502  \u2514\u2500 dagster 0.6.7.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.7 | 0.6.7 | 0.6.7 | 0.6.7 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.6 would require\n      \u2502  \u2514\u2500 dagster 0.6.6.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.6 | 0.6.6 | 0.6.6 | 0.6.6 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u251C\u2500 dagster_pandas 0.6.5 would require\n      \u2502  \u2514\u2500 dagster 0.6.5.*, which cannot be installed because there are no viable options:\n      \u2502     \u2514\u2500 dagster 0.6.5 | 0.6.5 | 0.6.5 | 0.6.5 would require\n      \u2502        \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n      \u2514\u2500 dagster_pandas 0.6.4 would require\n         \u2514\u2500 dagster 0.6.4.*, which cannot be installed because there are no viable options:\n            \u2514\u2500 dagster 0.6.4 | 0.6.4 | 0.6.4 would require\n               \u2514\u2500 enum-compat >=0.0.1, for which no candidates were found.\n\n                </pre>\n                </div>\n                </details>",
  "1.8.11": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/11320671204'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.8.11.*.\n\n</pre>\n</div>\n</details>",
  "1.8.12": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/11414992217\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 721, in _run_migrator_on_feedstock_branch\n    migrator_uid, pr_json = run_with_tmpdir(\n                            ^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 445, in run_with_tmpdir\n    return run(\n           ^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 547, in run\n    rerender_info = _run_rerender(\n                    ^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/auto_tick.py\", line 252, in _run_rerender\n    rerender_msg = rerender_feedstock(str(context.local_clone_dir), timeout=900)\n                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/cf-scripts/cf-scripts/cf-scripts/conda_forge_tick/rerender_feedstock.py\", line 24, in rerender_feedstock\n    return _rerender(feedstock_dir, timeout=timeout, use_container=use_container)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/rerender.py\", line 48, in rerender\n    return rerender_containerized(\n           ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/micromamba/envs/cf-scripts/lib/python3.11/site-packages/conda_forge_feedstock_ops/rerender.py\", line 116, in rerender_containerized\n    if data[\"commit_message\"] is not None and data[\"patch\"] is not None:\n                                              ~~~~^^^^^^^^^\nKeyError: 'patch'\n",
  "1.8.2": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10528616710'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.8.2.*.\n\n</pre>\n</div>\n</details>",
  "1.8.3": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10590712696'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.8.3.*.\n\n</pre>\n</div>\n</details>",
  "1.8.5": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/10758012697'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.8.5.*.\n\n</pre>\n</div>\n</details>",
  "1.9.0": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/11652897158'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.9.0.*.\n\n</pre>\n</div>\n</details>",
  "1.9.1": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/11794948905'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.9.1.*.\n\n</pre>\n</div>\n</details>",
  "1.9.10": "bot error (<a href=\"https://github.com/regro/cf-scripts/actions/runs/12953514509\">bot CI job</a>): main:\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 715, in urlopen\n    httplib_response = self._make_request(\n                       ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 467, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 462, in _make_request\n    httplib_response = conn.getresponse()\n                       ^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/http/client.py\", line 1395, in getresponse\n    response.begin()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/http/client.py\", line 325, in begin\n    version, status, reason = self._read_status()\n                              ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/http/client.py\", line 294, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/adapters.py\", line 667, in send\n    resp = conn.urlopen(\n           ^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 801, in urlopen\n    retries = retries.increment(\n              ^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/util/retry.py\", line 552, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 715, in urlopen\n    httplib_response = self._make_request(\n                       ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 467, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/urllib3/connectionpool.py\", line 462, in _make_request\n    httplib_response = conn.getresponse()\n                       ^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/http/client.py\", line 1395, in getresponse\n    response.begin()\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/http/client.py\", line 325, in begin\n    version, status, reason = self._read_status()\n                              ^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/http/client.py\", line 294, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nurllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 119, in _run_bot_task\n    data = func(attrs=attrs, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/container_cli.py\", line 225, in _migrate_feedstock\n    data = run_migration_local(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migration_runner.py\", line 260, in run_migration_local\n    data[\"pr_body\"] = migrator.pr_body(feedstock_ctx)\n                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 265, in pr_body\n    pred = [\n           ^\n  File \"/opt/autotick-bot/conda_forge_tick/migrators/version.py\", line 268, in <listcomp>\n    self.effective_graph.nodes[name][\"payload\"][\"version_pr_info\"][\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/lazy_json_backends.py\", line 1052, in __getitem__\n    self._load()\n  File \"/opt/autotick-bot/conda_forge_tick/lazy_json_backends.py\", line 1009, in _load\n    backend.hsetnx(self.hashmap, self.node, dumps({}))\n  File \"/opt/autotick-bot/conda_forge_tick/lazy_json_backends.py\", line 114, in hsetnx\n    if self.hexists(name, key):\n       ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/autotick-bot/conda_forge_tick/lazy_json_backends.py\", line 256, in hexists\n    status = requests.head(url, allow_redirects=True).status_code\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/api.py\", line 100, in head\n    return request(\"head\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/api.py\", line 59, in request\n    return session.request(method=method, url=url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py\", line 589, in request\n    resp = self.send(prep, **send_kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/sessions.py\", line 703, in send\n    r = adapter.send(request, **kwargs)\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/conda/envs/cf-scripts/lib/python3.11/site-packages/requests/adapters.py\", line 682, in send\n    raise ConnectionError(err, request=request)\nrequests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n",
  "1.9.2": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/11954805517'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.9.2.*.\n\n</pre>\n</div>\n</details>",
  "1.9.3": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/11988245825'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.9.3.*.\n\n</pre>\n</div>\n</details>",
  "1.9.4": "not solvable (<a href='https://github.com/regro/cf-scripts/actions/runs/12221535158'>bot CI job</a>) @ main\n<details>\n<div align=\"left\">\n<pre>\nlinux_64_: Cannot solve the request because of: No candidates were found for dagster-cloud-cli 1.9.4.*.\n\n</pre>\n</div>\n</details>"
 }
}